version: '1.0'
services:

  vault:
    build:
      dockerfile: Dockerfile.Vault
    container_name: Steam_statistics-Vaults
    volumes:
      - vault_data:/vault_data
    networks:
      - steam_statistics_etl_network
    ports:
      - "8200:8200"
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    restart: always

  postgresql:
    build:
      dockerfile: Dockerfile.PostgreSQL
    container_name: Steam_statistics-PostgreSQL
    depends_on:
      - vault
    networks:
      - steam_statistics_etl_network
    ports:
      - "8080:80"
      - "5432:5432"
    restart: always

#  luigi_etl:
#    build:
#      dockerfile: Dockerfile.Luigi_ETL
##      context: ./Steam_statistics_ETL/Docker
##      dockerfile: ./Steam_statistics_ETL/Docker/Luigi_ETL.df
#    container_name: Steam_statistics-Luigi_ETL
#    networks:
#      - steam_statistics_etl_network
#    depends_on:
#      - vault
#      - postgresql
#    restart: always
volumes:
  vault_data:

networks:
  steam_statistics_etl_network:
