version: '1.0'
services:

  vault:
    build:
      dockerfile: Vault.df
#      context: ./Steam_statistics_ETL/Docker
#      dockerfile: ./Steam_statistics_ETL/Docker/Vault.df
    container_name: Steam_statistics-Vaults
    ports:
      - "8200:8200"
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    restart: always

  postgresql:
    build:
      dockerfile: PostgreSQL.df
#      context: ./Steam_statistics_ETL/Docker
#      dockerfile: ./Steam_statistics_ETL/Docker/PostgreSQL.df
    container_name: Steam_statistics-PostgreSQL
    ports:
      - "8080:80"
      - "8201:8201"
    restart: always

  #Elastick_kash:

  luigi_etl:
    build:
      dockerfile: Luigi_ETL.df
#      context: ./Steam_statistics_ETL/Docker
#      dockerfile: ./Steam_statistics_ETL/Docker/Luigi_ETL.df
    container_name: Steam_statistics-Luigi_ETL
    restart: always
